openapi: 3.0.3
info:
  title: CustomerEic
  version: 0.2.0
  description: API to create, read, and update customer information.
tags:
  - name: CustomerEic
    description: API to create, read, and update customer information.
paths:
  /api/v1/customer/search:
    post:
      tags:
        - CustomerEic
      operationId: get-customer
      summary: Find a customer by identity
      security:
        - JWTAuth: [ ]
      parameters:
        - in: header
          name: x-document-date-time
          description: Document creation timestamp
          required: true
          schema:
            $ref: '#/components/schemas/dateTime'
        - in: header
          name: x-document-identification
          description: Document unique identification
          required: true
          schema:
            $ref: '#/components/schemas/uniqueId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                marketParticipantContext:
                  $ref: '#/components/schemas/marketParticipantContext'
                identity:
                  type: array
                  items:
                    $ref: '#/components/schemas/identity'
              required:
                - marketParticipantContext
                - identity
      description: >-
        Submit the customer identity to receive other identities and metadata
      responses:
        '200':
          description: OK
          headers:
            status:
              description: HTTP status code
              schema:
                $ref: '#/components/schemas/statusCode'
            x-document-date-time:
              description: Document creation timestamp
              schema:
                $ref: '#/components/schemas/dateTime'
            x-document-identification:
              description: Document unique identification
              schema:
                $ref: '#/components/schemas/uniqueId'
            x-original-document-identification:
              description: Request document unique identification
              schema:
                $ref: '#/components/schemas/uniqueId'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/customerWithPermissions'
        "400":
          $ref: '#/components/responses/badRequest'
        "401":
          $ref: '#/components/responses/unauthorized'
        "403":
          $ref: '#/components/responses/forbidden'
        "404":
          $ref: '#/components/responses/notFound'
        "422":
          $ref: '#/components/responses/unprocessableEntity'
  /api/v1/customer:
    post:
      tags:
        - CustomerEic
      operationId: request-customer
      summary: Create customer with metadata
      security:
        - JWTAuth: [ ]
      parameters:
        - in: header
          name: x-document-date-time
          description: Document creation timestamp
          required: true
          schema:
            $ref: '#/components/schemas/dateTime'
        - in: header
          name: x-document-identification
          description: Document unique identification
          required: true
          schema:
            $ref: '#/components/schemas/uniqueId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                marketParticipantContext:
                  $ref: '#/components/schemas/marketParticipantContext'
                customer:
                  type: array
                  items:
                    $ref: '#/components/schemas/customer'
              required:
                - marketParticipantContext
                - customer
        description: >-
          Submit the customer object to create the customer or identify the customer and update their metadata
      responses:
        '201':
          description: Created
          headers:
            status:
              description: HTTP status code
              schema:
                $ref: '#/components/schemas/statusCode'
            x-document-date-time:
              description: Document creation timestamp
              schema:
                $ref: '#/components/schemas/dateTime'
            x-document-identification:
              description: Document unique identification
              schema:
                $ref: '#/components/schemas/uniqueId'
            x-original-document-identification:
              description: Request document unique identification
              schema:
                $ref: '#/components/schemas/uniqueId'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/identity'
        "400":
          $ref: '#/components/responses/badRequest'
        "401":
          $ref: '#/components/responses/unauthorized'
        "403":
          $ref: '#/components/responses/forbidden'
        "422":
          $ref: '#/components/responses/unprocessableEntity'
    put:
      tags:
        - CustomerEic
      operationId: update-customer
      summary: Update customer identites or metadata
      security:
        - JWTAuth: [ ]
      parameters:
        - in: header
          name: x-document-date-time
          description: Document creation timestamp
          required: true
          schema:
            $ref: '#/components/schemas/dateTime'
        - in: header
          name: x-document-identification
          description: Document unique identification
          required: true
          schema:
            $ref: '#/components/schemas/uniqueId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                marketParticipantContext:
                  $ref: '#/components/schemas/marketParticipantContext'
                customer:
                  type: array
                  items:
                    $ref: '#/components/schemas/customer'
              required:
                - marketParticipantContext
                - customer
        description: >-
          Submit the customer object to identify the customer and update their metadata
      responses:
        '200':
          description: OK
          headers:
            status:
              description: HTTP status code
              schema:
                $ref: '#/components/schemas/statusCode'
            x-document-date-time:
              description: Document creation timestamp
              schema:
                $ref: '#/components/schemas/dateTime'
            x-document-identification:
              description: Document unique identification
              schema:
                $ref: '#/components/schemas/uniqueId'
            x-original-document-identification:
              description: Request document unique identification
              schema:
                $ref: '#/components/schemas/uniqueId'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/identity'
        "400":
          $ref: '#/components/responses/badRequest'
        "401":
          $ref: '#/components/responses/unauthorized'
        "403":
          $ref: '#/components/responses/forbidden'
        "404":
          $ref: '#/components/responses/notFound'
        "422":
          $ref: '#/components/responses/unprocessableEntity'
components:
  securitySchemes:
    JWTAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |-
        Example:
        > Authorization: Bearer <token>
  schemas:
    dateTime:
      type: string
      format: date-time
      description: ISO 8601 zone datetime
    uniqueId:
      type: string
      format: uuid
      description: UUID
    statusCode:
      type: integer
      description: HTTP status code
      minLength: 3
      maxLength: 3
    eic:
      type: string
      format: eic
      description: EIC code
      minLength: 16
      maxLength: 16
      # RegEx to verify the EIC format, semantic verification is part of content validation
      pattern: >-
        \d{2}[XYZWTVA][A-Z0-9\-]{12}[A-Z0-9]
    metadataType:
      type: string
      enum: [FIRST_NAME, LAST_NAME, COMPANY_NAME, PHONE, EMAIL]
    extensionType:
      type: string
      enum: [COUNTRY, ISSUER]
    customerType:
      type: string
      enum: [PHYSICAL_PERSON, LEGAL_PERSON, ORGANIZATION]
    identityType:
      type: string
      enum: [EIC, PERSONAL_ID, COMPANY_ID, DOCUMENT_ID, EMBASSY_ID]
    customer:
      type: object
      description: Customer object with identites and metadata
      properties:
        identities:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/identity'
        metadata:
          type: array
          items:
            $ref: '#/components/schemas/customerMetadata'
      required:
        - identities
    customerWithPermissions:
      type: object
      description: Customer object with identites and metadata
      properties:
        identities:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/identity'
        metadata:
          type: array
          items:
            $ref: '#/components/schemas/customerMetadata'
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/permission'
      required:
        - identities
    permission:
      type: object
      description: Permission block
      properties:
        meterEic:
          $ref: '#/components/schemas/eic'
        periodStart:
          $ref: '#/components/schemas/dateTime'
        periodEnd:
          $ref: '#/components/schemas/dateTime'
        subjectPeriodStart:
          $ref: '#/components/schemas/dateTime'
        subjectPeriodEnd:
          $ref: '#/components/schemas/dateTime'
        purpose:
          type: string
          maxLength: 50
      required:
        - meterEic
        - periodStart
        - periodEnd
        - subjectPeriodStart
        - subjectPeriodEnd
        - purpose
    identity:
      type: object
      description: Identity block
      properties:
        customerType:
          $ref: '#/components/schemas/customerType'
        identityType:
          $ref: '#/components/schemas/identityType'
        identityValue:
          type: string
          maxLength: 50
        identityExtension:
          type: array
          items:
            $ref: '#/components/schemas/identityExtension'
    identityExtension:
      type: object
      properties:
        extensionType:
          $ref: '#/components/schemas/extensionType'
        extensionValue:
          type: string
          maxLength: 250
      required:
        - extensionType
        - extensionValue
    customerMetadata:
      type: object
      properties:
        metadataType:
          $ref: '#/components/schemas/metadataType'
        metadataValue:
          type: string
          maxLength: 250
      required:
        - metadataType
        - metadataValue
    marketParticipantContext:
      type: object
      properties:
        marketParticipantIdentification:
          $ref: '#/components/schemas/eic'
        marketParticipantRole:
          type: string
          maxLength: 50
        purpose:
          type: string
          maxLength: 50
        commodityType:
          type: string
          enum: [ELECTRICITY, NATURAL_GAS]
      required:
        - marketParticipantIdentification
        - marketParticipantRole
        - commodityType
    badRequest:
      type: object
      description: Bad Request
      properties:
        problem:
          $ref: '#/components/schemas/defaultProblem'
    unauthorized:
      type: object
      description: Unauthorized
      properties:
        problem:
          $ref: '#/components/schemas/defaultProblem'
    forbidden:
      type: object
      description: Forbidden
      properties:
        problem:
          $ref: '#/components/schemas/defaultProblem'
    notFound:
      type: object
      description: Not found
      properties:
        problem:
          $ref: '#/components/schemas/defaultProblem'
    unprocessableEntity:
      type: object
      description: Unprocessable entity
      properties:
        problem:
          $ref: '#/components/schemas/defaultProblem'
    defaultProblem:
      type: object
      description: Default problem object
      properties:
        code:
          type: string
        message:
          type: string
        cause:
          $ref: '#/components/schemas/defaultProblem'
  responses:
    badRequest:
      description: Bad Request
      headers:
        status:
          description: HTTP status code
          schema:
            $ref: '#/components/schemas/statusCode'
        x-document-date-time:
          description: Document creation timestamp
          schema:
            $ref: '#/components/schemas/dateTime'
        x-document-identification:
          description: Document unique identification
          schema:
            $ref: '#/components/schemas/uniqueId'
        x-original-document-identification:
          description: Request document unique identification
          schema:
            $ref: '#/components/schemas/uniqueId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/badRequest'
    unauthorized:
      description: Unauthorized
      headers:
        status:
          description: HTTP status code
          schema:
            $ref: '#/components/schemas/statusCode'
        x-document-date-time:
          description: Document creation timestamp
          schema:
            $ref: '#/components/schemas/dateTime'
        x-document-identification:
          description: Document unique identification
          schema:
            $ref: '#/components/schemas/uniqueId'
        x-original-document-identification:
          description: Request document unique identification
          schema:
            $ref: '#/components/schemas/uniqueId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/unauthorized'
    forbidden:
      description: Forbidden
      headers:
        status:
          description: HTTP status code
          schema:
            $ref: '#/components/schemas/statusCode'
        x-document-date-time:
          description: Document creation timestamp
          schema:
            $ref: '#/components/schemas/dateTime'
        x-document-identification:
          description: Document unique identification
          schema:
            $ref: '#/components/schemas/uniqueId'
        x-original-document-identification:
          description: Request document unique identification
          schema:
            $ref: '#/components/schemas/uniqueId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/forbidden'
    notFound:
      description: Not found
      headers:
        status:
          description: HTTP status code
          schema:
            $ref: '#/components/schemas/statusCode'
        x-document-date-time:
          description: Document creation timestamp
          schema:
            $ref: '#/components/schemas/dateTime'
        x-document-identification:
          description: Document unique identification
          schema:
            $ref: '#/components/schemas/uniqueId'
        x-original-document-identification:
          description: Request document unique identification
          schema:
            $ref: '#/components/schemas/uniqueId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/notFound'
    unprocessableEntity:
      description: Unprocessable entity
      headers:
        status:
          description: HTTP status code
          schema:
            $ref: '#/components/schemas/statusCode'
        x-document-date-time:
          description: Document creation timestamp
          schema:
            $ref: '#/components/schemas/dateTime'
        x-document-identification:
          description: Document unique identification
          schema:
            $ref: '#/components/schemas/uniqueId'
        x-original-document-identification:
          description: Request document unique identification
          schema:
            $ref: '#/components/schemas/uniqueId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/unprocessableEntity'
servers:
  - url: https://test-newavp.elering.ee
security:
  - JWTAuth: [ ]