openapi: 3.0.3
info:
  title: DataDistribution
  version: 0.3.0
  description: API to read data distributions.
tags:
  - name: DataDistribution
    description: API to read data distributions.
paths:
  /api/v1/data-distribution/search:
    post:
      tags:
        - DataDistribution
      operationId: find-data-distributions
      summary: Find data distributions.
      security:
        - JWTAuth: [ ]
      parameters:
        - in: header
          name: x-document-date-time
          description: Document creation timestamp
          required: true
          schema:
            $ref: '#/components/schemas/dateTime'
        - in: header
          name: x-document-identification
          description: Document unique identification
          required: true
          schema:
            $ref: '#/components/schemas/uniqueId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                marketParticipantContext:
                  $ref: '#/components/schemas/marketParticipantContext'
                dataDistributionAttributes:
                  $ref: '#/components/schemas/dataDistributionAttributes'
                pagination:
                  $ref: '#/components/schemas/pagingRequest'
              required:
                - marketParticipantContext
                - dataDistributionAttributes
                - pagination
      responses:
        '200':
          description: OK
          headers:
            status:
              description: HTTP status code
              schema:
                $ref: '#/components/schemas/statusCode'
            x-document-date-time:
              description: Document creation timestamp
              schema:
                $ref: '#/components/schemas/dateTime'
            x-document-identification:
              description: Document unique identification
              schema:
                $ref: '#/components/schemas/uniqueId'
            x-original-document-identification:
              description: Request document unique identification
              schema:
                $ref: '#/components/schemas/uniqueId'
          content:
            application/json:
              schema:
                type: object
                properties:
                  dataDistributions:
                    type: array
                    items:
                      $ref: '#/components/schemas/dataDistributionListItem'
                  pagination:
                    $ref: '#/components/schemas/pagingResponse'
                required:
                  - dataDistributions
                  - pagination
        "400":
          $ref: '#/components/schemas/badRequest'
        "401":
          $ref: '#/components/schemas/unauthorized'
        "403":
          $ref: '#/components/schemas/forbidden'
        "404":
          $ref: '#/components/schemas/notFound'
        "422":
          $ref: '#/components/schemas/unprocessableEntity'
components:
  securitySchemes:
    JWTAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |-
        Example:
        > Authorization: Bearer <token>
  schemas:
    uniqueId:
      type: string
      format: uuid
      description: UUID
    statusCode:
      type: integer
      description: HTTP status code
      minLength: 3
      maxLength: 3
    dateTime:
      type: string
      format: date-time
      description: ISO 8601 zone datetime
    resourceType:
      type: string
      enum: [ METERING_POINT, METERING_DATA, NETWORK_BILL, JOINT_INVOICE, CUSTOMER, AGREEMENT, REPORT ]
    dataDistributionAttributes:
      type: object
      properties:
        createdTimeFrom:
          $ref: '#/components/schemas/dateTime'
        createdTimeTo:
          $ref: '#/components/schemas/dateTime'
        resourceType:
          $ref: '#/components/schemas/resourceType'
      required:
        - createdTimeFrom
        - createdTimeTo
        - resourceType
    dataDistributionListItem:
      type: object
      properties:
        createdTime:
          $ref: '#/components/schemas/dateTime'
        lastModifiedTime:
          $ref: '#/components/schemas/dateTime'
        resourceType:
          $ref: '#/components/schemas/resourceType'
        reason:
          type: string
        content:
          type: object
    marketParticipantContext:
      type: object
      properties:
        marketParticipantIdentification:
          $ref: '#/components/schemas/eic'
        marketParticipantRole:
          $ref: '#/components/schemas/serviceProviderRole'
        commodityType:
          $ref: '#/components/schemas/commodityType'
      required:
        - marketParticipantIdentification
        - marketParticipantRole
        - commodityType
    pagingRequest:
      type: object
      description: Pagination controls
      properties:
        page:
          type: integer
          minimum: 0
        pageSize:
          type: integer
          minimum: 1
      required:
        - page
        - pageSize
    pagingResponse:
      type: object
      description: Pagination controls
      properties:
        page:
          type: integer
          minimum: 0
        totalPages:
          type: integer
          minimum: 1
    eic:
      type: string
      format: eic
      description: EIC code
      minLength: 16
      maxLength: 16
      # RegEx to verify the EIC format, semantic verification is part of content validation
      pattern: >-
        \d{2}[XYZWTVA][A-Z0-9\-]{12}[A-Z0-9]
    serviceProviderRole:
      type: string
      enum: [ OPEN_SUPPLIER, GRID_OPERATOR, LINE_OPERATOR, CLOSED_DISTRIBUTION_NETWORK, PRODUCER_OPERATOR, CHARGING_POINT_OPERATOR, AGGREGATOR,  ENERGY_SERVICE_PROVIDER ]
    commodityType:
      type: string
      enum: [ ELECTRICITY, NATURAL_GAS ]
    badRequest:
      type: object
      description: Bad Request
      properties:
        problem:
          $ref: '#/components/schemas/defaultProblem'
    unauthorized:
      type: object
      description: Unauthorized
      properties:
        problem:
          $ref: '#/components/schemas/defaultProblem'
    forbidden:
      type: object
      description: Forbidden
      properties:
        problem:
          $ref: '#/components/schemas/defaultProblem'
    notFound:
      type: object
      description: Not found
      properties:
        problem:
          $ref: '#/components/schemas/defaultProblem'
    unprocessableEntity:
      type: object
      description: Unprocessable entity
      properties:
        problem:
          $ref: '#/components/schemas/defaultProblem'
    defaultProblem:
      type: object
      description: Default problem object
      properties:
        code:
          type: string
        message:
          type: string
        cause:
          $ref: '#/components/schemas/defaultProblem'
servers:
  - url: https://test-datahub.elering.ee
security:
  - JWTAuth: [ ]
