openapi: 3.0.3
info:
  title: NetworkBill
  version: 0.1.0
  description: API to create, read, and update network bills.
tags:
  - name: NetworkBill
    description: API to create, read, and update network bills.
paths:
  /api/v1/network-bill:
    post:
      tags:
        - NetworkBill
      operationId: create-network-bill-data
      summary: Create or update network bill data
      security:
        - JWTAuth: [ ]
      parameters:
        - in: header
          name: x-document-date-time
          description: Document creation timestamp
          required: true
          schema:
            $ref: '#/components/schemas/dateTime'
        - in: header
          name: x-document-identification
          description: Document unique identification
          required: true
          schema:
            $ref: '#/components/schemas/uniqueId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                marketParticipantContext:
                  $ref: '#/components/schemas/marketParticipantContext'
                networkBillTimeSeries:
                  type: object
                  title: CreateNetworkBillRequestTimeSeries
                  allOf:
                    - $ref: '#/components/schemas/networkBillTimeSeries'
                    - properties:
                        networkBillPeriod:
                          type: object
                          title: CreateNetworkBillRequestPeriod
                          properties:
                            calculationTimestamp:
                              $ref: '#/components/schemas/dateTime'
                            periodStart:
                              $ref: '#/components/schemas/dateTime'
                            periodEnd:
                              $ref: '#/components/schemas/dateTime'
                            containsCalculatedValues:
                              type: boolean
                            measurements:
                              type: array
                              items:
                                $ref: '#/components/schemas/measurement'
                              minItems: 1
                          required:
                            - calculationTimestamp
                            - periodStart
                            - periodEnd
                            - containsCalculatedValues
                            - measurements
                  required:
                    - meterEic
                    - commodityType
                    - networkBillPeriod
              required:
                - marketParticipantContext
                - networkBillTimeSeries
        description: >-
          Submit the network bill data object to create or update the meter report
      responses:
        '201':
          description: Created
          headers:
            status:
              description: HTTP status code
              schema:
                $ref: '#/components/schemas/statusCode'
            x-document-date-time:
              description: Document creation timestamp
              schema:
                $ref: '#/components/schemas/dateTime'
            x-document-identification:
              description: Document unique identification
              schema:
                $ref: '#/components/schemas/uniqueId'
            x-original-document-identification:
              description: Request document unique identification
              schema:
                $ref: '#/components/schemas/uniqueId'
          content:
            application/json:
              schema:
                type: object
                properties:
                  successful:
                    type: string
                required:
                  - successful
        "400":
          $ref: '#/components/schemas/badRequest'
        "401":
          $ref: '#/components/schemas/unauthorized'
        "403":
          $ref: '#/components/schemas/forbidden'
        "422":
          $ref: '#/components/schemas/unprocessableEntity'
  /api/v1/network-bill/search:
    post:
      tags:
        - NetworkBill
      operationId: find-network-bill-data
      summary: Find network bill data by meter EIC, period, and optionally billing sequence
      security:
        - JWTAuth: [ ]
      parameters:
        - in: header
          name: x-document-date-time
          description: Document creation timestamp
          required: true
          schema:
            $ref: '#/components/schemas/dateTime'
        - in: header
          name: x-document-identification
          description: Document unique identification
          required: true
          schema:
            $ref: '#/components/schemas/uniqueId'
      requestBody:
        required: true
        description: Submit the needed network bill and search metadata attributes.
        content:
          application/json:
            schema:
              type: object
              properties:
                marketParticipantContext:
                  $ref: '#/components/schemas/marketParticipantContext'
                networkBillAttributes:
                  $ref: '#/components/schemas/networkBillAttributes'
                pagination:
                  $ref: '#/components/schemas/pagingRequest'
              required:
                - marketParticipantContext
                - networkBillAttributes
                - pagination
      responses:
        '200':
          description: OK
          headers:
            status:
              description: HTTP status code
              schema:
                $ref: '#/components/schemas/statusCode'
            x-document-date-time:
              description: Document creation timestamp
              schema:
                $ref: '#/components/schemas/dateTime'
            x-document-identification:
              description: Document unique identification
              schema:
                $ref: '#/components/schemas/uniqueId'
            x-original-document-identification:
              description: Request document unique identification
              schema:
                $ref: '#/components/schemas/uniqueId'
          content:
            application/json:
              schema:
                type: object
                properties:
                  networkBillList:
                    type: array
                    items:
                      $ref: '#/components/schemas/networkBill'
                  pagination:
                    $ref: '#/components/schemas/pagingResponse'
                required:
                  - networkBillList
                  - pagination
        "400":
          $ref: '#/components/schemas/badRequest'
        "401":
          $ref: '#/components/schemas/unauthorized'
        "403":
          $ref: '#/components/schemas/forbidden'
        "404":
          $ref: '#/components/schemas/notFound'
        "422":
          $ref: '#/components/schemas/unprocessableEntity'
components:
  securitySchemes:
    JWTAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |-
        Example:
        > Authorization: Bearer <token>
  schemas:
    networkBillTimeSeries:
      type: object
      properties:
        meterEic:
          $ref: '#/components/schemas/eic'
        commodityType:
          $ref: '#/components/schemas/commodityType'
        networkBillPeriod:
          $ref: '#/components/schemas/networkBillPeriod'
      required:
        - meterEic
        - commodityType
        - networkBillPeriod
    networkBillAttributes:
      type: object
      properties:
        meterEic:
          $ref: '#/components/schemas/eic'
        periodStart:
          $ref: '#/components/schemas/dateTime'
        periodEnd:
          $ref: '#/components/schemas/dateTime'
        direction:
          $ref: '#/components/schemas/direction'
      required:
        - meterEic
        - periodStart
        - periodEnd
    networkBill:
      type: object
      properties:
        meterEic:
          $ref: '#/components/schemas/eic'
        networkBillPeriod:
          $ref: '#/components/schemas/networkBillPeriod'
      required:
        - meterEic
        - networkBillPeriod
    networkBillPeriod:
      type: object
      properties:
        calculationTimestamp:
          $ref: '#/components/schemas/dateTime'
        periodStart:
          $ref: '#/components/schemas/dateTime'
        periodEnd:
          $ref: '#/components/schemas/dateTime'
        containsCalculatedValues:
          type: boolean
        measurement:
          $ref: '#/components/schemas/measurement'
      required:
        - calculationTimestamp
        - periodStart
        - periodEnd
        - containsCalculatedValues
        - measurement
    measurement:
      type: object
      properties:
        direction:
          $ref: '#/components/schemas/direction'
        measurementUnit:
          $ref: '#/components/schemas/measurementUnit'
        day:
          $ref: '#/components/schemas/decimal'
        night:
          $ref: '#/components/schemas/decimal'
        total:
          $ref: '#/components/schemas/decimal'
      required:
        - direction
        - measurementUnit
        - day
        - night
        - total
    decimal:
      type: number
    measurementUnit:
      type: string
      enum: [ KWH, M3 ]
    direction:
      type: string
      enum: [ IN, OUT ]
    dateTime:
      type: string
      format: date-time
      description: ISO 8601 zone datetime
    uniqueId:
      type: string
      format: uuid
      description: UUID
    eic:
      type: string
      format: eic
      description: EIC code
      minLength: 16
      maxLength: 16
      # RegEx to verify the EIC format, semantic verification is part of content validation
      pattern: >-
        \d{2}[XYZWTVA][A-Z0-9\-]{12}[A-Z0-9]
    pagingRequest:
      type: object
      description: Pagination controls
      properties:
        page:
          type: integer
          minimum: 0
        pageSize:
          type: integer
          minimum: 1
      required:
        - page
        - pageSize
    pagingResponse:
      type: object
      description: Pagination controls
      properties:
        page:
          type: integer
          minimum: 0
        totalPages:
          type: integer
          minimum: 1
    commodityType:
      type: string
      enum: [ ELECTRICITY, NATURAL_GAS ]
    serviceProviderRole:
      type: string
      enum: [ OPEN_SUPPLIER, GRID_OPERATOR, LINE_OPERATOR, CLOSED_DISTRIBUTION_NETWORK, PRODUCER_OPERATOR, CHARGING_POINT_OPERATOR, AGGREGATOR,  ENERGY_SERVICE_PROVIDER ]
    marketParticipantContext:
      type: object
      properties:
        marketParticipantIdentification:
          $ref: '#/components/schemas/eic'
        marketParticipantRole:
          $ref: '#/components/schemas/serviceProviderRole'
        commodityType:
          $ref: '#/components/schemas/commodityType'
      required:
        - marketParticipantIdentification
        - marketParticipantRole
        - commodityType
    statusCode:
      type: integer
      description: HTTP status code
    badRequest:
      type: object
      description: Bad Request
      properties:
        problem:
          $ref: '#/components/schemas/defaultProblem'
    unauthorized:
      type: object
      description: Unauthorized
      properties:
        problem:
          $ref: '#/components/schemas/defaultProblem'
    forbidden:
      type: object
      description: Forbidden
      properties:
        problem:
          $ref: '#/components/schemas/defaultProblem'
    notFound:
      type: object
      description: Not found
      properties:
        problem:
          $ref: '#/components/schemas/defaultProblem'
    unprocessableEntity:
      type: object
      description: Unprocessable entity
      properties:
        problem:
          $ref: '#/components/schemas/defaultProblem'
    defaultProblem:
      type: object
      description: Default problem object
      properties:
        code:
          type: string
        message:
          type: string
        cause:
          $ref: '#/components/schemas/defaultProblem'
servers:
  - url: https://test-datahub.elering.ee
security:
  - JWTAuth: [ ]
